# Generated by Django 4.1.7 on 2023-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "ss",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=20)),
                ("prenom", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="machine",
            old_name="PC",
            new_name="IP",
        ),
    ]
