# Generated by Django 4.1.7 on 2023-04-15 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0003_rename_ss_personnel_social_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run Windows"),
                    ("Mac", "%AC - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server toi deploy virtual machines"),
                    ("Switch", "Switch - To maintain and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 11, 52, 30, 532077)
            ),
        ),
    ]
