# Generated by Django 4.1.7 on 2023-04-15 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0005_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 12, 34, 17, 461550)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="social_security",
            field=models.CharField(
                editable=False, max_length=13, primary_key=True, serialize=False
            ),
        ),
    ]
