# Generated by Django 4.1.7 on 2023-04-15 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0006_alter_machine_maintenancedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 12, 42, 2, 352343)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="social_security",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
