# Generated by Django 4.1.7 on 2023-04-15 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0007_alter_machine_maintenancedate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personnel",
            old_name="social_security",
            new_name="socialsecurity",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 15, 13, 47, 26, 264738)
            ),
        ),
    ]
