# Generated by Django 4.1.7 on 2023-04-16 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computerApp",
            "0008_rename_social_security_personnel_socialsecurity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 16, 7, 59, 12, 774498)
            ),
        ),
    ]
