# Generated by Django 4.1.7 on 2023-05-04 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0010_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="IP",
            field=models.GenericIPAddressField(default="192.168.0.1"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 7, 47, 15, 737286)
            ),
        ),
    ]
