# Generated by Django 4.1.7 on 2023-05-04 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0011_alter_machine_ip_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 7, 54, 4, 598475)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="socialsecurity",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
