# Generated by Django 4.1.7 on 2023-05-25 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0059_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 25, 13, 38, 23, 106221)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="nom",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="socialsecurity",
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
